version: '2.1'

services:
  web:
    restart: always
    build: ./web
    ports:
      - "${WEB_PORT}:8000"
    volumes:
      - ./web:/usr/src/app
    env_file: my.env
    environment:
      DEBUG: 'true'
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn docker_django.wsgi:application --reload -w 2 -b :8000"

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./web/static:/www/static
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    links:
      - web:web

  redis:
    restart: always
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
      
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-vol:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d/

volumes:
  mysql-vol:
  redisdata:
